import type { Metadata } from "next";
import "./globals.css";
import AppStateProvider from "@/app/components/AppState/AppState.context";
import { robotoSlab } from "@/app/fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <AppStateProvider>
        <body className={robotoSlab.className}>{children}</body>
      </AppStateProvider>
    </html>
  );
}
